# Generated by Django 3.0 on 2022-06-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='titile',
            new_name='title',
        ),
    ]
