# Generated by Django 3.0 on 2022-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220604_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
