# Generated by Django 3.0 on 2022-06-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20220604_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
