# Generated by Django 3.0 on 2022-06-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20220604_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
