# Generated by Django 3.0 on 2022-06-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220604_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
