# Generated by Django 3.0 on 2022-06-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_complaint_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='got_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
