# Generated by Django 3.0 on 2022-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20220604_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oppurtunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('conducted_by', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('I', 'INTERNSHIP'), ('O', 'ONLINE COURSE'), ('J', 'JOB')], max_length=2)),
                ('description', models.TextField()),
            ],
        ),
    ]
