# Generated by Django 3.0 on 2022-06-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_oppurtunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppurtunities',
            name='contact_number',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oppurtunities',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oppurtunities',
            name='genre',
            field=models.CharField(choices=[('I', 'INTERNSHIP'), ('J', 'JOB'), ('O', 'ONLINE COURSE')], max_length=2),
        ),
    ]
