# Generated by Django 3.0 on 2022-06-04 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0010_auto_20220604_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oppurtunities',
            name='genre',
            field=models.CharField(choices=[('I', 'INTERNSHIP'), ('O', 'ONLINE COURSE'), ('J', 'JOB')], max_length=2),
        ),
        migrations.CreateModel(
            name='ApplyOppurtunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=10)),
                ('institution', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
