# Generated by Django 3.0 on 2022-06-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20220604_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyoppurtunity',
            name='institution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='oppurtunities',
            name='genre',
            field=models.CharField(choices=[('J', 'JOB'), ('I', 'INTERNSHIP'), ('O', 'ONLINE COURSE')], max_length=2),
        ),
    ]
